# Generated by Django 2.2.5 on 2019-10-27 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0002_auto_20190922_2326'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instructor',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('semester', 'course', 'section_name')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('last_name', 'first_name', 'nick_name')},
        ),
    ]
